#!/usr/bin/env bash
#

## Fix java applications
export _JAVA_AWT_WM_NONREPARENTING=1


################---------------- Workspaces ----------------################
bspc monitor -d I II III IV V VI VII

################---------------- bspwm config ----------------################
bspc config split_ratio                   0.51
bspc config single_monocle                true
bspc config borderless_monocle            false
bspc config gapless_monocle               false
bspc config border_width                  2

bspc config normal_border_color           "#b0b846"
bspc config focused_border_color          "#f28534"

bspc config focus_follows_pointer         true
bspc config pointer_follows_focus         false
bspc config pointer_motion_interval       5
bspc config pointer_modifier              mod4
bspc config pointer_action1               move
bspc config pointer_action2               resize_side
bspc config pointer_action3               resize_corner
bspc config corner_radius                 15

#bspc wm --adopt-orphans
bspc rule -a scratch sticky=on state=floating focus=on7df0f0

################---------------- launch rices ----------------################
# Set system vars for polybar
. SetSysVars

# Terminate already running polybar, eww, picom, sxhkd and dunst instances
processes=("picom" "polybar" "sxhkd")

for process in "${processes[@]}"; do
  if pidof -q "$process"; then
    pkill -9 -x "$process" > /dev/null; sleep 0.1
  fi
done

# Load colors, dunst, bars and/or eww widgets
. "$HOME"/.config/bspwm/Theme.sh

# Launch picom // If you have old hardware or encounter problems
# uncomment the picom "--legacy-backends" line and comment the current one.
picom -b --config "$HOME"/.config/bspwm/picom.conf --log-level=info --log-file=/var/log/picom.log

# picom --experimental-backends --config "$HOME"/.config/bspwm/picom.conf &

# Launch dunst notification daemon (maybe to remove)
# dunst -config "$HOME"/.config/bspwm/dunstrc &

# Set random wallpaper for actual rice
feh -z --no-fehbg --bg-fill "$HOME"/.config/bspwm/walls/

# Reload sxhkd daemon
sxhkd -c "$HOME"/.config/bspwm/sxhkdrc &

# Launch polkit (maybe to remove)
# pidof -q polkit-gnome-authentication-agent-1 || { /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 & }

# Fix cursor
xsetroot -cursor_name left_ptr

# vmware clipboard
vmware-user-suid-wrapper
